name: Deploy
on:
  workflow_dispatch: 
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 1. Pull Latest Code
        uses: actions/checkout@v4

      - name: 2. Install Dependencies
        run: npm install

      - name: 3. Build Extension Package
        # This generates a file like: name-version.vsix
        run: vsce package

      - name: 4. Publish to VS Marketplace
        # We tell it to publish the .vsix file we just made
        run: vsce publish -p ${{ secrets.DEPLOYMENT_KEY }} --packagePath $(ls *.vsix)
        env:
          VSCE_PAT: ${{ secrets.DEPLOYMENT_KEY }}

      - name: 5. Publish to Open-VSX
        # Note the change to OVSX_PAT environment variable
        run: ovsx publish -p ${{ secrets.openvsx_token }} $(ls *.vsix)
        env:
          OVSX_PAT: ${{ secrets.openvsx_token }}

      - name: 6. Cleanup Workspace
        if: always()
        run: |
          echo "Cleaning up build files..."
          rm -rf ./*
          rm -rf ./.??*